name: MarwariCorpus
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - attrs==25.4.0
      - automat==25.4.16
      - beautifulsoup4==4.14.2
      - bs4==0.0.2
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - constantly==23.10.4
      - cryptography==46.0.3
      - cssselect==1.3.0
      - defusedxml==0.7.1
      - filelock==3.20.0
      - hyperlink==21.0.0
      - idna==3.11
      - incremental==24.7.2
      - itemadapter==0.12.2
      - itemloaders==1.3.2
      - jmespath==1.0.1
      - lxml==6.0.2
      - packaging==25.0
      - parsel==1.10.0
      - protego==0.5.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydispatcher==2.0.7
      - pyopenssl==25.3.0
      - queuelib==1.8.0
      - requests==2.32.5
      - requests-file==3.0.1
      - scrapy==2.13.3
      - service-identity==24.2.0
      - soupsieve==2.8
      - tldextract==5.3.0
      - twisted==25.5.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - w3lib==2.3.1
      - zope-interface==8.0.1
prefix: /home/bhaashik/miniconda3/envs/MarwariCorpus
